Replace circleci with github actions
dbrgn/embedded-hal-mock pull request #50
Opened 2022-10-31 01:51 UTC by newAM

For #49, as far as I know github actions has to be used on the default branch before it will be available on other branches.

This tests with nightly - which isn't necessary for the `master` branch, but it doesn't hurt, and it keeps the CI files aligned.

2022-10-31 08:21 UTC, dbrgn requested changes
Thank you, looks good! Can you update the README as well? The badges still reference CircleCI.

2022-10-31 08:21 UTC, dbrgn commented on .github/actions/ci.yml
> +  workflow_dispatch:
Interesting, TIL!

2022-10-31 14:48 UTC, newAM commented
> Thank you, looks good! Can you update the README as well? The badges still reference CircleCI.

Good catch, done!

2022-11-01 14:09 UTC, dbrgn commented
Looks good! Let's merge this, to see if it works 🙂

2022-11-01 14:10 UTC, merged